export const FETCH_USERS = 'FETCH_USERS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const SET_SENTIMENT_RESULTS = 'SET_SENTIMENT_RESULTS'
export const SET_ENTITY_RESULTS = 'SET_ENTITY_RESULTS'
export const SET_RELATIONSHIP_RESULTS = 'SET_RELATIONSHIP_RESULTS'
export const SET_INITIAL_RESEARCH_RESULTS = 'SET_INITIAL_RESEARCH_RESULTS'

export const MOVE_ENTITY_UP = 'MOVE_ENTITY_UP'
export const MOVE_ENTITY_DOWN = 'MOVE_ENTITY_DOWN'
export const REMOVE_ENTITY = 'REMOVE_ENTITY'
export const SAVE_BOOKMARK = 'SAVE_BOOKMARK'
